### ISSUE TITLE
Resources NotFoundException

### ISSUE THREAD

**Issue by filol** [javiersantos/PiracyChecker#29]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests.
- [x] I have verified that I am using the latest version of PiracyChecker.
- [x] I have read over the documentation (before asking questions on how to do something).
- [x] I have given my issue a non-generic title.

###### Details
 - PiracyChecker version: `1.1`
 - Device OS version: `all`
 - Device Manufacturer: `all`
 - Device Name: `all`

###### Reproduction Steps

I have Proguard and shrinkressource activate. 

```
Intent intent = new Intent(MainMenu.this, LicenseActivity.class)
                .putExtra("content", msg)
                .putExtra("colorPrimary", ContextCompat.getColor(this,R.color.green_500))
                .putExtra("colorPrimaryDark", ContextCompat.getColor(this,R.color.green_700));
        MainMenu.this.startActivity(intent);
        MainMenu.this.finish();
```

###### Expected Result

Work

###### Actual Result
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0xff4caf50
                      at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:190)
                      at android.content.res.Resources.getColor(Resources.java:922)
                      at android.content.Context.getColor(Context.java:508)
                      at android.support.v4.content.b.c(ContextCompat.java:411)
                      at com.github.javiersantos.piracychecker.activities.LicenseActivity.setActivityStyle(LicenseActivity.java:48)
                      at com.github.javiersantos.piracychecker.activities.LicenseActivity.onCreate(LicenseActivity.java:29)

**Comment by javiersantos** [comment]
You can't start the `LicenseActivity` activity manually as it is ready to be called from the library. You  should implement your own `Activity` when a custom callback is used.
