### ISSUE TITLE
Unnecessary dependency on Android Support Library v7

### ISSUE THREAD

**Issue by ThomasCZ** [javiersantos/PiracyChecker#3]
`Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                                at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:343)
                                                                                at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:312)
                                                                                at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:277)
                                                                                at android.support.v7.app.AppCompatDialog.setContentView(AppCompatDialog.java:80)
                                                                                at android.support.v7.app.AlertController.installContent(AlertController.java:214)
                                                                                at android.support.v7.app.AlertDialog.onCreate(AlertDialog.java:256)
                                                                                at android.app.Dialog.dispatchOnCreate(Dialog.java:578)
                                                                                at android.app.Dialog.show(Dialog.java:314)
                                                                                at com.github.javiersantos.piracychecker.PiracyChecker$1.dontAllow(PiracyChecker.java:78)
                                                                                at com.github.javiersantos.piracychecker.PiracyChecker.verify(PiracyChecker.java:86)
                                                                                at com.github.javiersantos.piracychecker.PiracyChecker.start(PiracyChecker.java:72)`

**Comment by javiersantos** [comment]
Are you using an `AppCompat` style in your `Activity`? See this sample:

_AndroidManifest.xml_
```xml
<application>
        ...
        android:theme="@style/AppTheme" >
        <activity>
            ....
        </activity>
        ...
</application>
```

_styles.xml_
```xml
<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        ...
</style>
```

**Comment by javiersantos** [comment]
I'm going to close this issue for now since I haven't received any answer. If you need additional help, please open it again.

**Comment by ThomasCZ** [comment]
I know how to fix to, but dependency on Android Support Library v7 is useless.
