### ISSUE TITLE
Crash in showing dialog

### ISSUE THREAD

**Issue by MatteCarra** [javiersantos/PiracyChecker#64]
###### Details
 - PiracyChecker version: `1.2.4`
 - Device OS version: `pie`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `Mi 5s`
(tested on an other huawei device running android 8 I think)
###### Builder
```Java
        checker = new PiracyChecker(this)
                .saveResultToSharedPreferences(preferences.getSharedPrefs(), "valid_license")
                .enableUnauthorizedAppsCheck(true)
                .enableGooglePlayLicensing("PRIVATE");

        checker.start();
```

###### Reproduction Steps

1. install LuckyPatcher
2. Open the app running PrivacyChecker

```
    java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter savedInstanceState
        at com.github.javiersantos.piracychecker.PiracyCheckerDialog.onCreateDialog(Unknown Source:2)
        at android.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:411)
        at android.app.Fragment.performGetLayoutInflater(Fragment.java:1339)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1298)
        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2426)
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2205)
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2161)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2062)
        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:738)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by MatteCarra** [comment]
This bug is not there in branch "ax".

**Comment by jahirfiquitiva** [comment]
Thanks for mentioning the issue is not present in the `ax` branch. You can [update to version 1.2.5](https://github.com/javiersantos/PiracyChecker/releases/tag/1.2.5) which is a merge of it.  :)
