### ISSUE TITLE
Issue with Strict Mode - Google Play Pre-Launch

### ISSUE THREAD

**Issue by avipars** [javiersantos/PiracyChecker#86]
I am using Google Play's Pre-Launch Report and got this warning: 

Unsupported
 8 warnings identified
The following APIs are greylisted and Google can’t guarantee that they will work on existing versions of Android. Some may be already be restricted for your target SDK

Most of the warnings come from the license activity. Here is the stacktrace: 

 StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/graphics/FontFamily;-><init>()V
	at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredConstructorInternal(Class.java)
	at java.lang.Class.getConstructor0(Class.java:2329)
	at java.lang.Class.getConstructor(Class.java:1728)
	at androidx.core.graphics.TypefaceCompatApi26Impl.obtainFontFamilyCtor(TypefaceCompatApi26Impl.java:2)
	at androidx.core.graphics.TypefaceCompatApi26Impl.<init>(TypefaceCompatApi26Impl.java:2)
	at androidx.core.graphics.TypefaceCompatApi28Impl.<init>(TypefaceCompatApi28Impl.java:0)
	at androidx.core.graphics.TypefaceCompat.<clinit>(TypefaceCompat.java:8)
	at androidx.core.graphics.TypefaceCompat.create(TypefaceCompat.java:0)
	at androidx.core.graphics.TypefaceCompat.createFromResourcesFontFile(TypefaceCompat.java:0)
	at androidx.core.graphics.TypefaceCompat.createResourceUid(TypefaceCompat.java:0)
	at androidx.appcompat.widget.AppCompatTextView.setTypeface(AppCompatTextView.java:8)
	at android.widget.TextView.resolveStyleAndSetTypeface(TextView.java:2162)
	at android.widget.TextView.setTypefaceFromAttrs(TextView.java:2133)
	at android.widget.TextView.applyTextAppearance(TextView.java:4080)
	at android.widget.TextView.<init>(TextView.java:1609)
	at android.widget.TextView.<init>(TextView.java:970)
	at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:3)
	at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:3)
	at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:2)
	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:255)
	at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:3)
	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:3)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1061)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
	at com.github.javiersantos.piracychecker.activities.LicenseActivity.setActivityData(LicenseActivity.java:15)
	at com.github.javiersantos.piracychecker.activities.LicenseActivity.onCreate(LicenseActivity.java:15)
	at android.app.Activity.performCreate(Activity.java:7825)
	at android.app.Activity.performCreate(Activity.java:7814)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:14)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by avipars** [comment]
Nonetheless, I have a test device with Android 10 and another with Android 9, both of them work fine.

**Comment by avipars** [comment]
There were several other warnings for the same activity.
